### ISSUE TITLE
Vue?

### ISSUE THREAD

**Issue by tm898989** [tekihei2317/zenn-contents#1]
Limit句やOffset句を使ってVueでページネーションを実装するのは無意味ですね
VueやApiまで使って実装するなら1000件くらい迄のデータを取ってきてフロントエンドでページネーションするのが正しい実装方法かと思います

PHPのようなバックエンドで実装するならまだしも
ページを切り替えるたびにAPIと通信するというのはVueのようなSPAを使う意味がないと思います

Vue+ページネーションで検索したらこのページがトップに出てきたのでちょっとびっくりしてます

**Comment by tekihei2317** [comment]
コメントありがとうございます。

1000件くらい取得するのが正しい実装なのですね。考えてみたところ、もし5000件あったとしても後ろのほうは見ないことのが多い気がするので、それをページネーションに表示しないことを許すのであれば、tm898989さんのおっしゃっている方法がページ遷移が高速な良いやり方になると思います。ただ、APIと通信する処理が十分高速であれば、記事に書いたやり方でもユーザー体験には問題ないのかなと思いました。

ちなみに1000件というのは、ネットワークの転送量が問題にならない程度の件数ということでしょうか？

（検索結果については私はコントロールできないのでお許しいただければと;;）

**Comment by tm898989** [comment]
**>APIと通信する処理が十分高速であれば、記事に書いたやり方でもユーザー体験には問題ないのかなと思いました。**
もちろん問題ありませんし間違ってるとも思いません
実際、古くからあるPHPのフレームワークではページネーション機能はこの記事のように実装してあります。
Laravelで使うようなページネーションを実装するのならこの記事は参考になると思いますね。
ちなみにLaravelでVueが利用できるようになったことを最近知りました。

**>ちなみに1000件というのは、ネットワークの転送量が問題にならない程度の件数ということでしょうか？**
これは1ページ10件表示だとして100ページもの検索結果は誰も見ないだろうなあという自分の勝手な感覚ですね
1万件くらい迄ならどんな弱いサーバーでも余裕かなって思いました。

_最近Vueやいろんなライブラリが増えてきてわけもわからず新しいものを使いたがる人が多くてちょっと愚痴っぽくなっていました、すいません_

**Comment by tekihei2317** [comment]
この方法が一番いいだろうと思い込んでしまっていたので、勉強になりました😀
要件やユーザー体験を考えて選択しようと思います。
ご意見ありがとうございました！
